// Papa Ke Jamane Ke Gaane - 81 songs
const songs = [
  "Asha Bhosle, Mohammed Rafi - Abhi Na Jao Chhod Kar.mp3",
  "Mohammed Rafi - Ek Pardesi Mera Dil Le Gaya.mp3",
  "Kishore Kumar - Jab Koi Baat Bigad Jaye.mp3",
  "Kishore Kumar - Yeh Vaada Raha.mp3",
  "Kishore Kumar - Naam Goom Jayega.mp3",
  "Kishore Kumar - Tum Itna Jo Muskura Rahe Ho.mp3",
  "Kishore Kumar - Zindagi Pyar Ka Geet Hai.mp3",
  "Lata Mangeshkar - Ye Zamin Gaa Rahi Hai (Teri Kasam).mp3",
  "Kishore Kumar - Dekha Ek Khwab.mp3",
  "Kishore Kumar - Aajkal Tere Mere Pyar Ke Charche.mp3",
  "Kishore Kumar - Neele Neele Ambar Par (Male Version).mp3",
  "Mohammed Rafi - Chura Liya Hai Tumne Jo Dil Ko.mp3",
  "Kishore Kumar - Jaane Kya Baat Hai.mp3",
  "Altaf Raja - Dono Hi Mohabbat Ke.mp3",
  "Manna Dey - Do Lafzon Ki Hai Dil Ki Kahani.mp3",
  "Asha Bhosle - Kajra Mohabbat Wala.mp3",
  "Kishore Kumar - Saagar Kinare.mp3",
  "Kishore Kumar - Taarif Karoon Kya Uski.mp3",
  "Udit Narayan, Alka Yagnik - Pardesi Pardesi.mp3",
  "Kishore Kumar - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Manmohan Singh - Mere Pyar Ki Umar Ho Itnee Sanam.mp3",
  "Kishore Kumar - Mehbooba Mehbooba.mp3",
  "Lata Mangeshkar - Luka Chuppi.mp3",
  "Kishore Kumar - O Mere Dil Ke Chain.mp3",
  "Lata Mangeshkar - Bade Achhe Lagte Hain.mp3",
  "Mohammed Rafi - Ajib Dastan Hai Yeh.mp3",
  "Kumar Sanu - Mera Dil Bhi Kitna Pagal Hai.mp3",
  "Kumar Sanu - Aaye Ho Meri Zindagi Mein.mp3",
  "Lata Mangeshkar, Kishore Kumar - Salame Ishq Meri Jaan.mp3",
  "Mukesh & Lata Mangeshkar - Kabhi Kabhi Mere Dil Mein (Duet).mp3",
  "Kumar Sanu, Alka Yagnik - Mujhse Mohabbat Ka.mp3",
  "Mohammed Rafi - Huzoor Is Kadar.mp3",
  "Kishore Kumar - Agar Tum Na Hote (Male Version).mp3",
  "Kumar Sanu, Anuradha Paudwal - Dheere Dheere Se Meri Zindagi Mein Aana.mp3",
  "Kishore Kumar - Neele Neele Ambar Par.mp3",
  "Alka Yagnik, Udit Narayan - Ae Mere Humsafar.mp3",
  "Kishore Kumar - Saagar Jaisi Aankhonwali.mp3",
  "Mukesh - Main Pal Do Pal Ka Shair Hoon With Dialogue By Amitabh.mp3",
  "Kishore Kumar - Hum Aap Ki Ankhon Mein.mp3",
  "Lata Mangeshkar - Tujhse Naraz Nahin Zindagi.mp3",
  "Kishore Kumar - Dil Kya Kare.mp3",
  "Asha Bhosle, Mohammed Rafi - O Haseena Zulfonwale Jane Jahan.mp3",
  "Lata Mangeshkar - Maine Tere Liye.mp3",
  "Kishore Kumar - Dilbar Mere.mp3",
  "Kishore Kumar - Chhu Kar Mere Manko.mp3",
  "Kishore Kumar - Hum Bewafa Hargiz Na Thay.mp3",
  "Kishore Kumar, Lata Mangeshkar - Gore Rang Pe Itna Gumaan Na Kar.mp3",
  "Kishore Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Kishore Kumar - Pal Pal Dil Ke Paas.mp3",
  "Kishore Kumar - Kitne Bhi Tu Karle Sitam.mp3",
  "Lata Mangeshkar, Mukesh - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Kishore Kumar - Dekha Ek Khwab.mp3",
  "Lata Mangeshkar - Ham Tere Pyar Mein.mp3",
  "Talat Mahmood - Itna Na Mujhse Tu Pyar Badha.mp3",
  "Jagjit Singh - Tum Ko Dekha To Yeh Khayal Aaya.mp3",
  "Mohammed Rafi - Aane Se Uske Aaye Bahar.mp3",
  "Mohammed Rafi - Chahoonga Main Tujhe.mp3",
  "Kishore Kumar - Mere Mehboob Qayamat Hogi.mp3",
  "Kishore Kumar - Aa Chal Ke Tujhe.mp3",
  "Asha Bhosle, Mohammed Rafi - Achha Ji Main Haari Chalo.mp3",
  "Mohammed Rafi, Sushma Shrestha - Kya Hua Tera Vada.mp3",
  "Lata Mangeshkar - Aaja Piya Tohe Pyar Doon.mp3",
  "Kishore Kumar - Kuchh To Log Kahenge.mp3",
  "Mohammed Rafi - Likhe Jo Khat Tujhe.mp3",
  "Lata Mangeshkar - Tera Mera Pyar Amar.mp3",
  "Mohammed Rafi - Main Zindagi Ka Saath Nibhata Chala Gaya.mp3",
  "Kishore Kumar - Meri Bheegi Bheegi Si.mp3",
  "Jagjit Singh - Hothon Se Chhu Lo Tum.mp3",
  "Lata Mangeshkar - Mere Khwabon Mein.mp3",
  "Mohammed Rafi - Gulabi Ankhen.mp3",
  "Kishore Kumar, Asha Bhosle - Yeh Raatein Yeh Mausam.mp3",
  "Kishore Kumar - Kiska Rasta Dekhe.mp3",
  "Asha Bhosle, Mohammed Rafi - Abhi Na Jao Chhod Kar.mp3",
  "Hemant Kumar - Hai Apna Dil To Awara.mp3",
  "Kishore Kumar - Ek Ajnabee Haseena Se.mp3",
  "Lata Mangeshkar - Lag Ja Gale Se Phir.mp3",
  "Mukesh, Kanchan - Kya Khoob Lagti Ho.mp3",
  "Hemant Kumar - Jane Woh Kaise Log The (2).mp3",
  "Hemant Kumar - Jane Woh Kaise Log The.mp3",
  "Hemant Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Hemant Kumar - Na Tum Hamen Jano.mp3"
];

// Bhojpuri Banger - Merged (Bhojpuri Tadka + Bihari Banger) - 105 songs
const bhojpuriSongs = [
  "Khesari Lal Yadav - Baap Ji.mp3",
  "Manoj Tiwari - Bhaiya Ji Kahie.mp3",
  "Panchayat - Ghaas Phus.mp3",
  "Nirahua - Nirahua Satal Rahe.mp3",
  "Nirahua - Hamra Pati Ka Hai Dhandha.mp3",
  "Khesari Lal Yadav - Maarela Kachaakach.mp3",
  "Manoj Tiwari - Kahiya Le Hoi Gawanwa.mp3",
  "Manoj Tiwari - Uparwali Ke Chakkar Mein.mp3",
  "Arvind Akela Kallu - Chita Ke Aag.mp3",
  "Arvind Akela Kallu - Ae Ganesh Ke Papa.mp3",
  "Khesari Lal Yadav - Piyawa Gaye Re Pardes.mp3",
  "Manoj Tiwari - Choli Ke Saiz.mp3",
  "Kalpana Patowary - Biraha Bihari Folk.mp3",
  "T-Series Hamaar Bhojpuri - Maarela Kachaakach.mp3",
  "Arvind Akela Kallu - Muai Dihala Rajaji.mp3",
  "Manoj Tiwari - Chatden Mar Deli Kheench Ke Tamacha.mp3",
  "Manoj Tiwari - Bagalwali Jaan Maareli.mp3",
  "Pawan Singh - Lolipop Lagelu.mp3",
  "Pawan Singh - Stuti Chhath Maiya.mp3",
  "Khesari Lal Yadav - Band Kar Generator.mp3",
  "Nirahua - Phool Aisan Chehra.mp3",
  "Khesari Lal Yadav - Lehnga Utha Deb.mp3",
  "Khesari Lal Yadav - Jawani Murgi Bhail Ba.mp3",
  "Nirahua - Border.mp3",
  "Manoj Tiwari - International Litti Chokha.mp3",
  "Manoj Tiwari - Gorakhiya Baba.mp3",
  "Gangs of Wasseypur - Taar Bijli.mp3",
  "Neelkamal Singh - Machhari.mp3",
  "Khesari Lal Yadav - Coke Cola.mp3",
  "Khesari Lal Yadav - Cocacola 2.mp3",
  "Gangs of Wasseypur - Hunter.mp3",
  "Manoj Tiwari - Eee Humra Bihar Ha.mp3",
  "Khesari Lal Yadav - Chachi Keachi.mp3",
  "Khesari Lal Yadav - Doodh Lassi.mp3",
  "Arvind Akela Kallu - Saari Ke Paloo.mp3",
  "Khesari Lal Yadav - Aasman Mein Sitare.mp3",
  "Khesari Lal Yadav - Marad Abhi Bachcha Ba.mp3",
  "Pawan Singh - Batawa Ae Gori Hamar.mp3",
  "Nirahua - Sipahi Title Song.mp3",
  "Khesari Lal Yadav - Jalebi.mp3",
  "Pawan Singh - Aara Ke Hothlali Lagalu.mp3",
  "RANGOLI FILMS - Band Kar Generator.mp3",
  "Neelkamal Singh - Kahe Tora Maie.mp3",
  "Panchayat - Hiya Ho.mp3",
  "Khesari Lal Yadav - Sutal Tani Kora Mein.mp3",
  "Pawan Singh - Girai Deh Pe Paani.mp3",
  "Nirahua - Table Par Loko.mp3",
  "Gangs of Wasseypur - O Womaniya.mp3",
  "Wave Music - Batawa Ae Gori Hamar.mp3",
  "Khesari Lal Yadav - Pagal Banaibe Ka.mp3",
  "Khesari Lal Yadav - Tabadala.mp3",
  "Khesari Lal Yadav - Nathunia.mp3",
  "Arvind Akela Kallu - Chala Pipra Ke Chhav.mp3",
  "Pawan Singh - Jag Hai Paaband.mp3",
  "Nirahua - Dinesh Lal Yadav.mp3",
  "T-Series Hamaar Bhojpuri - Lehanga Utha Dem.mp3",
  "Pramod Premi Yadav - Ae Rani Aao.mp3",
  "Khesari Lal Yadav - Bhatar Ko Bhi Bhul Jaoge.mp3",
  "Khesari Lal Yadav - Garaiya Machhari.mp3",
  "Khesari Lal Yadav - Dhamaka Hoile Ba.mp3",
  "Pramod Premi Yadav - Bhatar Ohi Me.mp3",
  "Manoj Tiwari - Baby Birchha.mp3",
  "Arvind Akela Kallu - Jawani Ke Halwa.mp3",
  "Awadhesh Premi Yadav - Rahi Baithal Kera Khatir.mp3",
  "Gangs of Wasseypur - Moora.mp3",
  "Saurav Yadav Official - Yadav Ji Khatal Me.mp3",
  "Neelkamal Singh - Laika Khelaee ki Tohke.mp3",
  "Pawan Singh - Jamana Kahela Pawan Singh.mp3",
  "Pawan Singh - Chhalakata Hamro Jawaniya.mp3",
  "Manoj Tiwari - Nayan Tarasne.mp3",
  "Pawan Singh - Dhani Ho Sab Dhan.mp3",
  "Neelkamal Singh - Jagahe Pa Jata.mp3",
  "Khesari Lal Yadav - Bhatar Katani.mp3",
  "Gangs of Wasseypur - Jiya Tu Bihar Ke Lala.mp3",
  "Arvind Akela Kallu - Naach Re Patarki 2.mp3",
  "Munna Premi - Upar Ke 32 Niche Ke 36.mp3",
  "Khesari Lal Yadav - Table Par Loko.mp3",
  "Gangs of Wasseypur - Tumni.mp3",
  "Pawan Singh - Lahangwa Lehab Odhani Se.mp3",
  "Pawan Singh - Kamariya Patre Patre.mp3",
  "Pawan Singh - Bas Kar Pagli.mp3",
  "Neelkamal Singh - Kahe Sochela.mp3",
  "Gangs of Wasseypur - Keh Ke Lunga.mp3",
  "Pawan Singh - Emerald Green Odhani.mp3",
  "Arvind Akela Kallu - Kamariya Bola Hey.mp3",
  "Gangs of Wasseypur - Saaiyaan.mp3",
  "Pawan Singh - Crack Fighter.mp3",
  "Arvind Akela Kallu - Tukur Tukur Dekha Na.mp3",
  "Pawan Singh - Ye Ladki Sahi Hai.mp3",
  "Arvind Akela Kallu - Chadhate Phagunwa.mp3",
  "Khesari Lal Yadav - Chumma De Da.mp3",
  "Arvind Akela Kallu - Dhan Kutani.mp3",
  "Khesari Lal Yadav - Ladki Patana.mp3",
  "Arvind Akela Kallu - Dil Me Ba Khesari.mp3",
  "Wave Music Bhojpuri - Saj Ke Sawar Ke.mp3",
  "Khesari Lal Yadav - Saj Ke Sawar Ke.mp3",
  "Akash Pal - Bihar Boy.mp3",
  "Pawan Singh - Falana Bo Amwa Na Khati.mp3",
  "Gangs of Wasseypur - Electric Piya.mp3",
  "Worldwide Records Bhojpuri - Sorry Sorry.mp3",
  "Khesari Lal Yadav - Sorry Sorry.mp3",
  "ChunChun Toons - Pahin Ke Chale Bikini.mp3",
  "Manoj Tiwari - Gopala Gopala.mp3",
  "Panchayat - Panchayat.mp3",
  "Panchayat - Dekh Raha Hai Binod.mp3"
];
