// Papa Ke Jamane Ke Gaane - 81 songs
const songs = [
  "Asha Bhosle, Mohammed Rafi - Abhi Na Jao Chhod Kar.mp3",
  "Mohammed Rafi - Ek Pardesi Mera Dil Le Gaya.mp3",
  "Kishore Kumar - Jab Koi Baat Bigad Jaye.mp3",
  "Kishore Kumar - Yeh Vaada Raha.mp3",
  "Kishore Kumar - Naam Goom Jayega.mp3",
  "Kishore Kumar - Tum Itna Jo Muskura Rahe Ho.mp3",
  "Kishore Kumar - Zindagi Pyar Ka Geet Hai.mp3",
  "Lata Mangeshkar - Ye Zamin Gaa Rahi Hai (Teri Kasam).mp3",
  "Kishore Kumar - Dekha Ek Khwab.mp3",
  "Kishore Kumar - Aajkal Tere Mere Pyar Ke Charche.mp3",
  "Kishore Kumar - Neele Neele Ambar Par (Male Version).mp3",
  "Mohammed Rafi - Chura Liya Hai Tumne Jo Dil Ko.mp3",
  "Kishore Kumar - Jaane Kya Baat Hai.mp3",
  "Altaf Raja - Dono Hi Mohabbat Ke.mp3",
  "Manna Dey - Do Lafzon Ki Hai Dil Ki Kahani.mp3",
  "Asha Bhosle - Kajra Mohabbat Wala.mp3",
  "Kishore Kumar - Saagar Kinare.mp3",
  "Kishore Kumar - Taarif Karoon Kya Uski.mp3",
  "Udit Narayan, Alka Yagnik - Pardesi Pardesi.mp3",
  "Kishore Kumar - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Manmohan Singh - Mere Pyar Ki Umar Ho Itnee Sanam.mp3",
  "Kishore Kumar - Mehbooba Mehbooba.mp3",
  "Lata Mangeshkar - Luka Chuppi.mp3",
  "Kishore Kumar - O Mere Dil Ke Chain.mp3",
  "Lata Mangeshkar - Bade Achhe Lagte Hain.mp3",
  "Mohammed Rafi - Ajib Dastan Hai Yeh.mp3",
  "Kumar Sanu - Mera Dil Bhi Kitna Pagal Hai.mp3",
  "Kumar Sanu - Aaye Ho Meri Zindagi Mein.mp3",
  "Lata Mangeshkar, Kishore Kumar - Salame Ishq Meri Jaan.mp3",
  "Mukesh & Lata Mangeshkar - Kabhi Kabhi Mere Dil Mein (Duet).mp3",
  "Kumar Sanu, Alka Yagnik - Mujhse Mohabbat Ka.mp3",
  "Mohammed Rafi - Huzoor Is Kadar.mp3",
  "Kishore Kumar - Agar Tum Na Hote (Male Version).mp3",
  "Kumar Sanu, Anuradha Paudwal - Dheere Dheere Se Meri Zindagi Mein Aana.mp3",
  "Kishore Kumar - Neele Neele Ambar Par.mp3",
  "Alka Yagnik, Udit Narayan - Ae Mere Humsafar.mp3",
  "Kishore Kumar - Saagar Jaisi Aankhonwali.mp3",
  "Mukesh - Main Pal Do Pal Ka Shair Hoon With Dialogue By Amitabh.mp3",
  "Kishore Kumar - Hum Aap Ki Ankhon Mein.mp3",
  "Lata Mangeshkar - Tujhse Naraz Nahin Zindagi.mp3",
  "Kishore Kumar - Dil Kya Kare.mp3",
  "Asha Bhosle, Mohammed Rafi - O Haseena Zulfonwale Jane Jahan.mp3",
  "Lata Mangeshkar - Maine Tere Liye.mp3",
  "Kishore Kumar - Dilbar Mere.mp3",
  "Kishore Kumar - Chhu Kar Mere Manko.mp3",
  "Kishore Kumar - Hum Bewafa Hargiz Na Thay.mp3",
  "Kishore Kumar, Lata Mangeshkar - Gore Rang Pe Itna Gumaan Na Kar.mp3",
  "Kishore Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Kishore Kumar - Pal Pal Dil Ke Paas.mp3",
  "Kishore Kumar - Kitne Bhi Tu Karle Sitam.mp3",
  "Lata Mangeshkar, Mukesh - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Kishore Kumar - Dekha Ek Khwab.mp3",
  "Lata Mangeshkar - Ham Tere Pyar Mein.mp3",
  "Talat Mahmood - Itna Na Mujhse Tu Pyar Badha.mp3",
  "Jagjit Singh - Tum Ko Dekha To Yeh Khayal Aaya.mp3",
  "Mohammed Rafi - Aane Se Uske Aaye Bahar.mp3",
  "Mohammed Rafi - Chahoonga Main Tujhe.mp3",
  "Kishore Kumar - Mere Mehboob Qayamat Hogi.mp3",
  "Kishore Kumar - Aa Chal Ke Tujhe.mp3",
  "Asha Bhosle, Mohammed Rafi - Achha Ji Main Haari Chalo.mp3",
  "Mohammed Rafi, Sushma Shrestha - Kya Hua Tera Vada.mp3",
  "Lata Mangeshkar - Aaja Piya Tohe Pyar Doon.mp3",
  "Kishore Kumar - Kuchh To Log Kahenge.mp3",
  "Mohammed Rafi - Likhe Jo Khat Tujhe.mp3",
  "Lata Mangeshkar - Tera Mera Pyar Amar.mp3",
  "Mohammed Rafi - Main Zindagi Ka Saath Nibhata Chala Gaya.mp3",
  "Kishore Kumar - Meri Bheegi Bheegi Si.mp3",
  "Jagjit Singh - Hothon Se Chhu Lo Tum.mp3",
  "Lata Mangeshkar - Mere Khwabon Mein.mp3",
  "Mohammed Rafi - Gulabi Ankhen.mp3",
  "Kishore Kumar, Asha Bhosle - Yeh Raatein Yeh Mausam.mp3",
  "Kishore Kumar - Kiska Rasta Dekhe.mp3",
  "Hemant Kumar - Hai Apna Dil To Awara.mp3",
  "Kishore Kumar - Ek Ajnabee Haseena Se.mp3",
  "Lata Mangeshkar - Lag Ja Gale Se Phir.mp3",
  "Mukesh, Kanchan - Kya Khoob Lagti Ho.mp3",
  "Hemant Kumar - Jane Woh Kaise Log The (2).mp3",
  "Hemant Kumar - Jane Woh Kaise Log The.mp3",
  "Hemant Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Hemant Kumar - Na Tum Hamen Jano.mp3"
];

// Bhojpuri Banger - Merged (Bhojpuri Tadka + Bihari Banger) - 105 songs
const bhojpuriSongs = [
  "Khesari Lal Yadav - Baap Ji.mp3",
  "Manoj Tiwari - Bhaiya Ji Kahie.mp3",
  "Panchayat - Ghaas Phus.mp3",
  "Nirahua - Nirahua Satal Rahe.mp3",
  "Nirahua - Hamra Pati Ka Hai Dhandha.mp3",
  "Khesari Lal Yadav - Maarela Kachaakach.mp3",
  "Manoj Tiwari - Kahiya Le Hoi Gawanwa.mp3",
  "Manoj Tiwari - Uparwali Ke Chakkar Mein.mp3",
  "Arvind Akela Kallu - Chita Ke Aag.mp3",
  "Arvind Akela Kallu - Ae Ganesh Ke Papa.mp3",
  "Khesari Lal Yadav - Piyawa Gaye Re Pardes.mp3",
  "Manoj Tiwari - Choli Ke Saiz.mp3",
  "Kalpana Patowary - Biraha Bihari Folk.mp3",
  "T-Series Hamaar Bhojpuri - Maarela Kachaakach.mp3",
  "Arvind Akela Kallu - Muai Dihala Rajaji.mp3",
  "Manoj Tiwari - Chatden Mar Deli Kheench Ke Tamacha.mp3",
  "Manoj Tiwari - Bagalwali Jaan Maareli.mp3",
  "Pawan Singh - Lolipop Lagelu.mp3",
  "Pawan Singh - Stuti Chhath Maiya.mp3",
  "Khesari Lal Yadav - Band Kar Generator.mp3",
  "Nirahua - Phool Aisan Chehra.mp3",
  "Khesari Lal Yadav - Lehnga Utha Deb.mp3",
  "Khesari Lal Yadav - Jawani Murgi Bhail Ba.mp3",
  "Nirahua - Border.mp3",
  "Manoj Tiwari - International Litti Chokha.mp3",
  "Manoj Tiwari - Gorakhiya Baba.mp3",
  "Gangs of Wasseypur - Taar Bijli.mp3",
  "Neelkamal Singh - Machhari.mp3",
  "Khesari Lal Yadav - Coke Cola.mp3",
  "Khesari Lal Yadav - Cocacola 2.mp3",
  "Gangs of Wasseypur - Hunter.mp3",
  "Manoj Tiwari - Eee Humra Bihar Ha.mp3",
  "Khesari Lal Yadav - Chachi Keachi.mp3",
  "Khesari Lal Yadav - Doodh Lassi.mp3",
  "Arvind Akela Kallu - Saari Ke Paloo.mp3",
  "Khesari Lal Yadav - Aasman Mein Sitare.mp3",
  "Khesari Lal Yadav - Marad Abhi Bachcha Ba.mp3",
  "Pawan Singh - Batawa Ae Gori Hamar.mp3",
  "Nirahua - Sipahi Title Song.mp3",
  "Khesari Lal Yadav - Jalebi.mp3",
  "Pawan Singh - Aara Ke Hothlali Lagalu.mp3",
  "RANGOLI FILMS - Band Kar Generator.mp3",
  "Neelkamal Singh - Kahe Tora Maie.mp3",
  "Panchayat - Hiya Ho.mp3",
  "Khesari Lal Yadav - Sutal Tani Kora Mein.mp3",
  "Pawan Singh - Girai Deh Pe Paani.mp3",
  "Nirahua - Table Par Loko.mp3",
  "Gangs of Wasseypur - O Womaniya.mp3",
  "Wave Music - Batawa Ae Gori Hamar.mp3",
  "Khesari Lal Yadav - Pagal Banaibe Ka.mp3",
  "Khesari Lal Yadav - Tabadala.mp3",
  "Khesari Lal Yadav - Nathunia.mp3",
  "Arvind Akela Kallu - Chala Pipra Ke Chhav.mp3",
  "Pawan Singh - Jag Hai Paaband.mp3",
  "Nirahua - Dinesh Lal Yadav.mp3",
  "T-Series Hamaar Bhojpuri - Lehanga Utha Dem.mp3",
  "Pramod Premi Yadav - Ae Rani Aao.mp3",
  "Khesari Lal Yadav - Bhatar Ko Bhi Bhul Jaoge.mp3",
  "Khesari Lal Yadav - Garaiya Machhari.mp3",
  "Khesari Lal Yadav - Dhamaka Hoile Ba.mp3",
  "Pramod Premi Yadav - Bhatar Ohi Me.mp3",
  "Manoj Tiwari - Baby Birchha.mp3",
  "Arvind Akela Kallu - Jawani Ke Halwa.mp3",
  "Awadhesh Premi Yadav - Rahi Baithal Kera Khatir.mp3",
  "Gangs of Wasseypur - Moora.mp3",
  "Saurav Yadav Official - Yadav Ji Khatal Me.mp3",
  "Neelkamal Singh - Laika Khelaee ki Tohke.mp3",
  "Pawan Singh - Jamana Kahela Pawan Singh.mp3",
  "Pawan Singh - Chhalakata Hamro Jawaniya.mp3",
  "Manoj Tiwari - Nayan Tarasne.mp3",
  "Pawan Singh - Dhani Ho Sab Dhan.mp3",
  "Neelkamal Singh - Jagahe Pa Jata.mp3",
  "Khesari Lal Yadav - Bhatar Katani.mp3",
  "Gangs of Wasseypur - Jiya Tu Bihar Ke Lala.mp3",
  "Arvind Akela Kallu - Naach Re Patarki 2.mp3",
  "Munna Premi - Upar Ke 32 Niche Ke 36.mp3",
  "Khesari Lal Yadav - Table Par Loko.mp3",
  "Gangs of Wasseypur - Tumni.mp3",
  "Pawan Singh - Lahangwa Lehab Odhani Se.mp3",
  "Pawan Singh - Kamariya Patre Patre.mp3",
  "Pawan Singh - Bas Kar Pagli.mp3",
  "Neelkamal Singh - Kahe Sochela.mp3",
  "Gangs of Wasseypur - Keh Ke Lunga.mp3",
  "Pawan Singh - Emerald Green Odhani.mp3",
  "Arvind Akela Kallu - Kamariya Bola Hey.mp3",
  "Gangs of Wasseypur - Saaiyaan.mp3",
  "Pawan Singh - Crack Fighter.mp3",
  "Arvind Akela Kallu - Tukur Tukur Dekha Na.mp3",
  "Pawan Singh - Ye Ladki Sahi Hai.mp3",
  "Arvind Akela Kallu - Chadhate Phagunwa.mp3",
  "Khesari Lal Yadav - Chumma De Da.mp3",
  "Arvind Akela Kallu - Dhan Kutani.mp3",
  "Khesari Lal Yadav - Ladki Patana.mp3",
  "Arvind Akela Kallu - Dil Me Ba Khesari.mp3",
  "Wave Music Bhojpuri - Saj Ke Sawar Ke.mp3",
  "Khesari Lal Yadav - Saj Ke Sawar Ke.mp3",
  "Akash Pal - Bihar Boy.mp3",
  "Pawan Singh - Falana Bo Amwa Na Khati.mp3",
  "Gangs of Wasseypur - Electric Piya.mp3",
  "Worldwide Records Bhojpuri - Sorry Sorry.mp3",
  "Khesari Lal Yadav - Sorry Sorry.mp3",
  "ChunChun Toons - Pahin Ke Chale Bikini.mp3",
  "Manoj Tiwari - Gopala Gopala.mp3",
  "Panchayat - Panchayat.mp3",
  "Panchayat - Dekh Raha Hai Binod.mp3"
];

const bartanSongs = [
  "Arijit Singh, Rajat Nagpal - Bachna Ae Haseeno.mp3",
  "Sadhana Sargam - Saat Samundar Paar.mp3",
  "Shaan & Shreya Ghoshal - Do U Know.mp3",
  "Zain Sam, Fazilpuria & Jyotica Tangri - Pallo Latke.mp3",
  "Benny Dayal - Locha-E-Ulfat.mp3",
  "Benny Dayal - Aadat Se Majboor.mp3",
  "K. S. Makhan - Good Luck Charm.mp3",
  "Manni Sandhu & Akhil - Gani.mp3",
  "Shreya Ghoshal - Latoo.mp3",
  "Shahid Mallya, Nisha Mascarenhas, Marianne D'Cruz - Kukkad.mp3",
  "Atif Aslam & Shreya Ghoshal - Tere Liye (Remix).mp3",
  "Akon & Hamsika Iyer - Chammak Challo.mp3",
  "Dr Zeus & Master Rakesh - Kangna.mp3",
  "J Star - Na Na Na Na.mp3",
  "Ajay-Atul, Shreya Ghoshal - Chikni Chameli.mp3",
  "Anand Raj Anand, Richa Sharma - Billo Rani.mp3",
  "Pritam, Rekha Bhardwaj, Vishal Dadlani - Ghagra.mp3",
  "Mika Singh, Sunidhi Chauhan - Aapka Kya Hoga (Dhanno).mp3",
  "Pritam, Neeraj Shridhar, Master Saleem, Suzanne D'Mello - Aahun Aahun.mp3",
  "Amit Trivedi, Vishal Dadlani - Chokra Jawaan.mp3",
  "Mamta Sharma, Wajid - Fevicol Se.mp3",
  "Vishal Dadlani - I Hate Luv Storys.mp3",
  "Pritam, KK, Hard Kaur - Main Tera Dhadkan Teri.mp3",
  "Mamta Sharma, Sukhwinder Singh - Anarkali Disco Chali.mp3",
  "Mika Singh, Dominique Cerejo - Baamulaiza.mp3",
  "Pritam, Mika Singh, Irshad Kamil - Mauja Hi Mauja.mp3",
  "Salim Merchant, Shruti Pathak - Ainvayi Ainvayi.mp3",
  "Vishal-Shekhar, Bappi Lahiri, Shreya Ghoshal - Ooh La La.mp3",
  "Pritam, Neeraj Shridhar - Twist.mp3",
  "Tarun Sagar, Alyssa Mendonsa - Oh Girl You're Mine.mp3",
  "Armaan Malik - Shanivaar Raati.mp3",
  "Sonu Nigam, Hema Sardesai - Yeh Dil Deewana.mp3",
  "Anu Malik, Alisha Chinai - Bebo.mp3",
  "Mamta Sharma, Aishwarya Nigam - Munni Badnaam Hui.mp3",
  "Benny Dayal, Neeti Mohan - Bang Bang.mp3",
  "Ash King, Neuman Pinto, Bianca Gomes - Aunty Ji.mp3",
  "Sukhwinder Singh, Vishal Dadlani - Dhan Te Nan.mp3",
  "Benny Dayal, Anushka Manchanda - Ek Main Aur Ekk Tu.mp3",
  "Sohail Sen, Ali Zafar, Shweta Pandit - Madhubala.mp3",
  "Ikka, Arko, Shraddha Pandit - Paani Wala Dance.mp3",
  "Vishal-Shekhar, Sunidhi Chauhan, Vishal Dadlani - Sheila Ki Jawani.mp3",
  "Yo Yo Honey Singh - Desi Kalakaar.mp3",
  "Arijit Singh - Palat Tera Hero Idhar Hai.mp3",
  "Amrita Kak, Mika Singh - Dhinka Chika.mp3",
  "Benny Dayal, Shalmali Kholgade - Besharmi Ki Height.mp3",
  "Pritam, Mika Singh, Shefali Alvares - Tu Mera Hero.mp3",
  "Vishal-Shekhar, Anushka Manchanda, Vishal Dadlani - Naughty Naughty.mp3",
  "Benny Dayal, Shalmali Kholgade - Lat Lag Gayee.mp3",
  "Suzanne D'Mello, Sowmya Raoh, Hrishikesh Kamerkar - Le Le Mazaa Le.mp3",
  "Asha Bhosle - Yeh Mera Dil Yaar Ka Deewana.mp3",
  "Yo Yo Honey Singh, Neha Kakkar - Sunny Sunny.mp3",
  "Manak-E, Selina, RDB - Paisa.mp3",
  "Neeti Mohan, Neeraj Shridhar - Caller Tune.mp3",
  "Neeti Mohan - Galat Baat Hai.mp3",
  "Pritam, Benny Dayal, Shalmali Kholgade - Daaru Desi.mp3",
  "Himesh Reshammiya, Vineet Singh - Hookah Bar.mp3",
  "Wajid, Sunidhi Chauhan, Suzanne D'Mello - Right Now Now.mp3",
  "Monali Thakur, Earl Edgar - Zara Zara Touch Me.mp3",
  "Pritam, Earl Edgar, Master Saleem, Vishal Dadlani - Make Some Noise for the Desi Boyz.mp3",
  "Pritam, Neeraj Shridhar, Bob - Bhool Bhulaiyaa.mp3",
  "Pritam, Nakash Aziz - Afghan Jalebi (Film Version).mp3",
  "Sunidhi Chauhan - Hotty Naughty.mp3",
  "Jaidev Kumar, Anmol Malik - Nagin Dance.mp3",
  "Yo Yo Honey Singh - Lungi Dance.mp3",
  "Yo Yo Honey Singh - Love Dose.mp3",
  "Sonu Nigam - Tees Maar Khan.mp3",
  "Pritam, Neeraj Shridhar, Suzanne D'Mello - Prem Ki Naiyya.mp3",
  "Shreya Ghoshal, Sriram Chandra - Balma.mp3",
  "Shaarib Toshi, Badshah - Saturday Saturday.mp3",
  "Sukhwinder Singh, Marianne D'Cruz - Dard-E-Disco.mp3",
  "Pritam, Miss Pooja, Harshdeep Kaur, Nakash Aziz - Second Hand Jawaani.mp3",
  "Pritam, Neeraj Shridhar, Sunidhi Chauhan - Chor Bazari.mp3",
  "Sachin-Jigar, Benny Dayal, Shirley Setia - Disco Disco.mp3",
  "Ram Sampath, Sona Mohapatra - Bedardi Raja.mp3",
  "Vishal-Shekhar, Shreya Ghoshal, Vishal Dadlani - Drama Queen.mp3",
  "Pritam, Sonu Nigam, Shilpa Rao - Allah Maaf Kare.mp3",
  "Pritam, Neeraj Shridhar, Amrita Kak - Character Dheela.mp3",
  "Vishal-Shekhar, Sunidhi Chauhan - Sajna Ji Vaari Vaari.mp3",
  "Sukhbir, Ikka - Oh Ho Ho Ho (Remix).mp3",
  "Neeraj Shridhar - Papa Toh Band Bajaye.mp3",
  "Sonu Nigam, Sunidhi Chauhan - Gustakh Dil Tere Liye.mp3",
  "Pritam, Mika Singh, Amitabh Bhattacharya - Pungi.mp3",
  "Asha Bhosle, Arijit Singh - Hungama Ho Gaya.mp3",
  "Yo Yo Honey Singh - Blue Eyes.mp3",
  "Mika Singh, Pritam - Tu Mere Agal Bagal Hai.mp3",
  "Sonu Nigam, Jayesh Gandhi, Amrita Kak - Just Chill.mp3",
  "Himesh Reshammiya, Yo Yo Honey Singh - Lonely.mp3",
  "Badshah, Aastha Gill - DJ Waley Babu.mp3",
  "Sachin-Jigar, Benny Dayal, Shalmali Kholgade - Lucky Tu Lucky Me.mp3",
  "Rekha Bhardwaj - Genda Phool.mp3",
  "Yo Yo Honey Singh - Party All Night.mp3",
  "Mamta Sharma, Meet Bros Anjjan - Pinky.mp3",
  "Ritu Pathak, Gaurika Rai, Anand Raj Anand - Jalebi Bai.mp3",
];

const genzSongs = [
  "Arijit Singh & Shreya Ghoshal - Raat Bhar.mp3",
  "Mohit Chauhan & Shreya Ghoshal - Is This Love.mp3",
  "Pritam, Atif Aslam & Alisha Chinai - Tera Hone Laga Hoon.mp3",
  "Pritam, Arijit Singh & Amitabh Bhattacharya - Deva Deva.mp3",
  "Amit Trivedi, Jasleen Royal & Kausar Munir - Love You Zindagi.mp3",
  "Sachin-Jigar & Raghav Chaitanya - Tum Se.mp3",
  "Mohammad Faiz & Jaani - Dekhha Tenu.mp3",
  "Sachin-Jigar, Arijit Singh & Amitabh Bhattacharya - Apna Bana Le.mp3",
  "Sohail Sen & Mudassar Aziz - Aashiq Tera.mp3",
  "Maanu & Annural Khalid - Jhol (Acoustic).mp3",
  "Jasleen Royal, Stebin Ben & Vijay Deverakonda - Sahiba.mp3",
  "Pritam, Arijit Singh & Amitabh Bhattacharya - Tere Pyaar Mein.mp3",
  "Pritam, Arijit Singh & Nikita Gandhi - Aavan Jaavan.mp3",
  "Pritam, Benny Dayal & Shefali Alvares - Badtameez Dil.mp3",
  "Jubin Nautiyal & Akashdeep Sengupta - Ishq Mera.mp3",
  "Aditya Rikhari & Tulsi Kumar - Jaana Samjho Na.mp3",
  "Darshan Raval, Aditya Gadhvi & Hansika Pareek - Sajna.mp3",
  "Arijit Singh & Shashwat Singh - Zamaana Lage.mp3",
  "Pitbull, Diljit Dosanjh & Neeraj Shridhar - Bhool Bhulaiyaa 3 (Title Track).mp3",
  "Sachin-Jigar, Pawan Singh & Simran Choudhary - Aayi Nai.mp3",
  "Jasleen Royal & Harshdeep Kaur - Nachde Ne Saare.mp3",
  "Sanam - Gulabi Aankhen.mp3",
  "Zain Zohaib - Ranjheya Ve.mp3",
  "Pritam, Mohit Chauhan & Amitabh Bhattacharya - Ilahi (Reprise).mp3",
  "Yo Yo Honey Singh & Simar Kaur - Laal Pari.mp3",
  "Sachet Tandon & Parampara Tandon - Maiyya.mp3",
  "Anuv Jain - Jo Tum Mere Ho.mp3",
  "Sachet Tandon & Parampara Tandon - Mere Sohneya.mp3",
  "Anirudh Ravichander & Arijit Singh - Chaleya.mp3",
  "Sanju Rathod & G-SPXRK - Shaky.mp3",
  "Jasleen Royal, Arijit Singh & Dulquer Salmaan - Heeriye.mp3",
  "Tanishk Bagchi, Yasser Desai & Asees Kaur - Makhna.mp3",
  "Anuv Jain & AP Dhillon - Afsos.mp3",
  "Juss & MixSingh - Suniyan Suniyan.mp3",
  "Faheem Abdullah & Rauhan Malik - Ishq.mp3",
  "Pritam, Arijit Singh & Amitabh Bhattacharya - Ilahi.mp3",
  "Taniskaa Sanghvi & Sachin-Jigar - Ek Zindagi.mp3",
  "Sachin-Jigar & Arijit Singh - Tainu Khabar Nahi.mp3",
  "Pritam & Tanishk Bagchi - Chor Bazari (Phir Se).mp3",
  "Arijit Singh & Shreya Ghoshal - Ve Kamleya.mp3",
  "Badshah & Arijit Singh - Soulmate.mp3",
  "Gurnazar & Chet Singh - Dil Tu Jaan Tu.mp3",
  "Iqlipse Nova & Prakriti Kakar - Tum Ho Toh.mp3",
  "Anuv Jain - Husn.mp3",
  "Tanishk Bagchi & Satinder Sartaaj - Rang.mp3",
  "Danny, Madhubanti Bagchi & Suyyash Rai - Chahvan Sohneya.mp3",
  "Jasleen Royal & Ujjwal Kashyap - Sang Rahiyo.mp3",
  "Iqlipse Nova & Adeetiya - Dil Besabar.mp3",
  "Bunny, Hunny & Sagar - Tu Hain Toh.mp3",
  "Sachin-Jigar, Sonu Nigam & Krishnakali Saha - Pardesiya.mp3",
  "Shubh - One Love.mp3",
  "Tanishk Bagchi, Gifty & Harnoor - Koi Naa.mp3",
  "Ed Sheeran - Sapphire.mp3",
  "Danny, Avvy Sra & Sagar - Ve Haaniyaan.mp3",
  "Sachin-Jigar, Raghav Chaitanya & Varun Jain - Teri Baaton Mein Aisa Uljha Jiya (Title Song).mp3",
  "Kushagra, Bharath & Saaheal - Finding Her.mp3",
  "Zuhair Ahmed - Maand.mp3",
  "Mitraz - Akhiyaan Gulaab.mp3",
  "Aparshakti Khurana - Zaroor.mp3",
  "The Rish & Shilpa Rao - Barbaad (Reprise Female).mp3",
  "Anurag Saikia, Raj Shekhar & Romy - Ishq Hai.mp3",
  "Iqlipse Nova & Aditya A - Khwab.mp3",
  "Akshath - Nadaaniyan.mp3",
  "Sachet Tandon & Parampara Tandon - Malang Sajna.mp3",
  "THE 9TEEN, Sandesh Shandilya - Aankhon Mein Doob Jaane Ko.mp3",
  "Aditya A - Chaand Baaliyan.mp3",
  "Iqlipse Nova & Hiten - Saawariya.mp3",
  "Aditya Rikhari - Paro.mp3",
];

const neendiSongs = [
  "Pritam & Shreya Ghoshal - Tabaah Ho Gaye.mp3",
  "Mithoon, Neeti Mohan & Vishal Mishra - Chal Tere Ishq Mein.mp3",
  "The Rish & Jubin Nautiyal - Barbaad.mp3",
  "Tanishk Bagchi & Faheem Abdullah - Saiyaara.mp3",
  "Pritam & Arijit Singh - Tumse Bhi Zyada.mp3",
  "Palak Muchhal, Arijit Singh & Jeet Gannguli - Chahun Main Ya Naa.mp3",
  "Sachet Tandon & Parampara Tandon - Humsafar.mp3",
  "Arijit Singh - Ishq Mubarak.mp3",
  "Vishal Mishra & Hansika Pareek - Tum Ho Toh.mp3",
  "Ved Sharma - Malang (Title Track).mp3",
  "Manan Bhardwaj, Sachet Tandon & Meera Bai - Simroon Tera Naam.mp3",
  "Arijit Singh & Asad Khan - Raanjhana.mp3",
  "Jeet Gannguli & Arijit Singh - Mera Pyar Tera Pyar.mp3",
  "Vishal Mishra, Kaushik Guddu & Kunaal Vermaa - Deewaniyat.mp3",
  "Himesh Reshammiya & Arijit Singh - Tera Chehra.mp3",
  "Arijit Singh - Yaad Hai Na.mp3",
  "Pritam & Arijit Singh - O Maahi.mp3",
  "Mithoon & Arijit Singh - Dhun.mp3",
  "Vishal Mishra - Aaj Bhi 2.mp3",
  "Jubin Nautiyal & Jeet Gannguli - Suna Hai.mp3",
  "Tanishk Bagchi, Vishal Mishra & Shilpa Rao - Jeena Haraam.mp3",
  "Payal Dev & Vishal Mishra - Naseeb Se.mp3",
];

const vibe2009Songs = [
  "Javed Ali & Kailash Kher - Arziyan.mp3",
  "Rahat Fateh Ali Khan - Jaoon Kahan.mp3",
  "Sukhwinder Singh & Sunidhi Chauhan - Marjaani.mp3",
  "Atif Aslam - Tu Jaane Na.mp3",
  "KK - Main Kya Hoon.mp3",
  "Soham Chakraborty, Akriti Kakkar & Monali Thakur - Khudaya Khair.mp3",
  "Sonu Nigam & Shreya Ghoshal - Shukran Allah.mp3",
  "Atif Aslam & Alisha Chinai - Tera Hone Laga Hoon.mp3",
  "Sukhwinder Singh & Kailash Kher - Dua.mp3",
  "Neeraj Shridhar - Twist.mp3",
  "Neeraj Shridhar & Suzanne D'Mello - Aahun Aahun.mp3",
  "Wajid & Earl D'Souza - Jalwa.mp3",
  "Vishal Dadlani - Kurbaan Hua.mp3",
  "Pritam Chakraborty & Bonnie Chakraborty - Gale Lag Ja.mp3",
  "Javed Ali & JoJo - Aa Jao Meri Tamanna.mp3",
  "Sunidhi Chauhan & Wajid - Love Me Love Me.mp3",
  "A. R. Rahman, Rashid Ali - Rehna Tu.mp3",
  "Neeraj Shridhar & Sunidhi Chauhan - Chor Bazaari.mp3",
  "Sunidhi Chauhan - Thoda Thoda Pyar.mp3",
  "Pritam, Sunidhi Chauhan, Sandeep Shrivastava - Mere Sang.mp3",
  "Sukhwinder Singh, Shreya Ghoshal - Aaj Dil Gustakh Hai.mp3",
  "Wajid - Tose Pyar Karte Hai.mp3",
  "Neeraj Shridhar - Lakh Lakh.mp3",
  "Pritam, Shafqat Amanat Ali - Tum Mile (Rock).mp3",
  "Vijay Prakash, Shreya Ghoshal, A. R. Rahman - Fiqrana.mp3",
  "KK, Shreya Ghoshal - Nazrein Karam.mp3",
  "Salim Merchant - Khudaya Ve.mp3",
  "Kylie Minogue, Sonu Nigam - Chiggy Wiggy.mp3",
  "Vishal Shekhar, Vishal Dadlani - You May Be.mp3",
  "Rahat Fateh Ali Khan - Aji Din Chadheya.mp3",
  "Pritam, Neeraj Shridhar - Love Mera Hit Hit.mp3",
  "Pritam, Suraj Jagan, Rupam Islam - Dil Kare.mp3",
  "Mohit Chauhan - Dooriyan.mp3",
  "Pritam, KK, Sandeep Shrivastava - Hai Junoon.mp3",
  "Vishal Dadlani, Roop Kumar Rathod - Barson Yaaron.mp3",
  "Shankar Mahadevan - Man Ko Ati Bhavey.mp3",
  "Pritam, Soham Chakraborty - Khudaya Khair.mp3",
  "Salim Sulaiman, Sukhwinder Singh, Kailash Kher - Dua.mp3",
  "Pritam, KK, Hard Kaur - Main Tera Dhadkan Teri.mp3",
  "Mohit Chauhan, Tulsi Kumar - Kuchh Is Tarah.mp3",
  "Rahat Fateh Ali Khan, Suzanne D'Mello - Rishte Naate.mp3",
  "Pritam, Neeraj Shridhar - You Get Me Rockin' & Reeling.mp3",
  "Salim Sulaiman, Sonu Nigam - Shukran Allah.mp3",
  "Shruti Pathak - Rasiya.mp3",
  "Vishal Dadlani - Nazaara Hai.mp3",
  "Emosanal Attyachaar (Brass Band Version).mp3",
  "Pritam, Javed Ali, Irshan Ashraf - Tu Hi Haqeeqat.mp3",
  "Alisha Chinai - Bebo.mp3",
  "Wajid, Sajid, Jalees Sherwani - Jalwa.mp3",
  "Shaarib Toshi, Toshi Sabri - Maahi.mp3",
  "RDB, Nindy Kaur - Aaloo Chaat (Title Track).mp3",
  "Neeraj Shridhar - Chor Bazari.mp3",
  "Sukhwinder Singh, Kailash Kher - Fatak.mp3",
  "KK - Aaya Re.mp3",
  "Amit Trivedi, Kavita Seth, Amitabh Bhattacharya - Iktara.mp3",
  "Mohan - Khanabadosh.mp3",
  "Shankar Mahadevan - Sapnon Se Bhare Naina.mp3",
  "RDB - Om Mangalam.mp3",
  "Mohit Chauhan, A. R. Rahman - Masakali.mp3",
  "Blaaze, Benny Dayal, Viviane, Tanvi Shah - Dilli-6.mp3",
  "Pritam, Mohit Chauhan - Tune Jo Na Kaha.mp3",
  "Shaan, Shreya Ghoshal - Kyun.mp3",
  "Sohail Sen, Shaan, Bhavya Pandit - Aaja Lehraate.mp3",
  "Salim Sulaiman, Salim Merchant - Ali Maula.mp3",
  "Sunidhi Chauhan, Shaan - Gazab.mp3",
  "Salim Sulaiman, Vishal Dadlani - Kurbaan Hua.mp3",
  "Shankar Mahadevan, Shreya Ghoshal - Tere Naina.mp3",
  "Sunidhi Chauhan - Hotty Naughty.mp3",
  "Pritam, Neeraj Shridhar, Suzanne D'Mello - Prem Ki Naiyya.mp3",
  "Kailash Kher - Aaloo Chaat.mp3",
  "Shankar Ehsaan Loy - Wake Up Sid!.mp3",
  "Manak-E, Selina - Paisa.mp3",
  "Soham Chakraborty, Suhail Kaul & Dominique Cerejo - Baamulaiza4.mp3",
  "Shankar Ehsaan Loy, Clinton Cerejo - Kya Karoon.mp3",
  "Shankar Ehsaan Loy - Aaj Kal Zindagi.mp3",
  "Shaan, Shreya Ghoshal, Sajid Wajid - Dil Leke.mp3",
  "Wajid, Amrita Kak, Sajid - Love Me Love Me.mp3",
  "Kamaal Khan, Sunidhi Chauhan - Ishq Vishq.mp3",
  "Hard Kaur, Pritam - Follow Me.mp3",
  "Shaan, Shantanu Moitra - Behti Hawa Sa Tha Woh.mp3",
  "Suraj Jagan, Sharman Joshi - Give Me Some Sunshine.mp3",
  "Shankar Ehsaan Loy, Uday Benegal - Life Is Crazy.mp3",
  "Sohail Sen, Bela Shende - Su Chhe.mp3",
  "Mohit Chauhan - Pehli Baar Mohabbat.mp3",
  "Sonu Nigam, Shreya Ghoshal - Zoobi Doobi.mp3",
  "Shilpa Rao - Mudhi Mudhi Ittefaq Se.mp3",
  "Sonu Nigam - Jaane Nahin Denge Tujhe.mp3",
  "Rekha Bhardwaj, A. R. Rahman - Genda Phool.mp3",
];

