const songs = [
  "Asha Bhosle, Mohammed Rafi - Abhi Na Jao Chhod Kar.mp3",
  "Mohammed Rafi - Ek Pardesi Mera Dil Le Gaya.mp3",
  "Kishore Kumar - Jab Koi Baat Bigad Jaye.mp3",
  "Kishore Kumar - Yeh Vaada Raha.mp3",
  "Kishore Kumar - Naam Goom Jayega.mp3",
  "Kishore Kumar - Tum Itna Jo Muskura Rahe Ho.mp3",
  "Kishore Kumar - Zindagi Pyar Ka Geet Hai.mp3",
  "Lata Mangeshkar - Ye Zamin Gaa Rahi Hai (Teri Kasam).mp3",
  "Kishore Kumar - Dekha Ek Khwab.mp3",
  "Kishore Kumar - Aajkal Tere Mere Pyar Ke Charche.mp3",
  "Kishore Kumar - Neele Neele Ambar Par (Male Version).mp3",
  "Mohammed Rafi - Chura Liya Hai Tumne Jo Dil Ko.mp3",
  "Kishore Kumar - Jaane Kya Baat Hai.mp3",
  "Altaf Raja - Dono Hi Mohabbat Ke.mp3",
  "Manna Dey - Do Lafzon Ki Hai Dil Ki Kahani.mp3",
  "Asha Bhosle - Kajra Mohabbat Wala.mp3",
  "Kishore Kumar - Saagar Kinare.mp3",
  "Kishore Kumar - Taarif Karoon Kya Uski.mp3",
  "Udit Narayan, Alka Yagnik - Pardesi Pardesi.mp3",
  "Kishore Kumar - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Manmohan Singh - Mere Pyar Ki Umar Ho Itnee Sanam.mp3",
  "Kishore Kumar - Mehbooba Mehbooba.mp3",
  "Lata Mangeshkar - Luka Chuppi.mp3",
  "Kishore Kumar - O Mere Dil Ke Chain.mp3",
  "Lata Mangeshkar - Bade Achhe Lagte Hain.mp3",
  "Mohammed Rafi - Ajib Dastan Hai Yeh.mp3",
  "Kumar Sanu - Mera Dil Bhi Kitna Pagal Hai.mp3",
  "Kumar Sanu - Aaye Ho Meri Zindagi Mein.mp3",
  "Lata Mangeshkar, Kishore Kumar - Salame Ishq Meri Jaan.mp3",
  "Mukesh & Lata Mangeshkar - Kabhi Kabhi Mere Dil Mein (Duet).mp3",
  "Kumar Sanu, Alka Yagnik - Mujhse Mohabbat Ka.mp3",
  "Mohammed Rafi - Huzoor Is Kadar.mp3",
  "Kishore Kumar - Agar Tum Na Hote (Male Version).mp3",
  "Kumar Sanu, Anuradha Paudwal - Dheere Dheere Se Meri Zindagi Mein Aana.mp3",
  "Kishore Kumar - Neele Neele Ambar Par.mp3",
  "Alka Yagnik, Udit Narayan - Ae Mere Humsafar.mp3",
  "Kishore Kumar - Saagar Jaisi Aankhonwali.mp3",
  "Mukesh - Main Pal Do Pal Ka Shair Hoon With Dialogue By Amitabh.mp3",
  "Kishore Kumar - Hum Aap Ki Ankhon Mein.mp3",
  "Lata Mangeshkar - Tujhse Naraz Nahin Zindagi.mp3",
  "Kishore Kumar - Dil Kya Kare.mp3",
  "Asha Bhosle, Mohammed Rafi - O Haseena Zulfonwale Jane Jahan.mp3",
  "Lata Mangeshkar - Maine Tere Liye.mp3",
  "Kishore Kumar - Dilbar Mere.mp3",
  "Kishore Kumar - Chhu Kar Mere Manko.mp3",
  "Kishore Kumar - Hum Bewafa Hargiz Na Thay.mp3",
  "Kishore Kumar, Lata Mangeshkar - Gore Rang Pe Itna Gumaan Na Kar.mp3",
  "Kishore Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Kishore Kumar - Pal Pal Dil Ke Paas.mp3",
  "Kishore Kumar - Kitne Bhi Tu Karle Sitam.mp3",
  "Lata Mangeshkar, Mukesh - Ek Pyar Ka Naghma Hai.mp3",
  "Lata Mangeshkar, Kishore Kumar - Dekha Ek Khwab.mp3",
  "Lata Mangeshkar - Ham Tere Pyar Mein.mp3",
  "Talat Mahmood - Itna Na Mujhse Tu Pyar Badha.mp3",
  "Jagjit Singh - Tum Ko Dekha To Yeh Khayal Aaya.mp3",
  "Mohammed Rafi - Aane Se Uske Aaye Bahar.mp3",
  "Mohammed Rafi - Chahoonga Main Tujhe.mp3",
  "Kishore Kumar - Mere Mehboob Qayamat Hogi.mp3",
  "Kishore Kumar - Aa Chal Ke Tujhe.mp3",
  "Asha Bhosle, Mohammed Rafi - Achha Ji Main Haari Chalo.mp3",
  "Mohammed Rafi, Sushma Shrestha - Kya Hua Tera Vada.mp3",
  "Lata Mangeshkar - Aaja Piya Tohe Pyar Doon.mp3",
  "Kishore Kumar - Kuchh To Log Kahenge.mp3",
  "Mohammed Rafi - Likhe Jo Khat Tujhe.mp3",
  "Lata Mangeshkar - Tera Mera Pyar Amar.mp3",
  "Mohammed Rafi - Main Zindagi Ka Saath Nibhata Chala Gaya.mp3",
  "Kishore Kumar - Meri Bheegi Bheegi Si.mp3",
  "Jagjit Singh - Hothon Se Chhu Lo Tum.mp3",
  "Lata Mangeshkar - Mere Khwabon Mein.mp3",
  "Mohammed Rafi - Gulabi Ankhen.mp3",
  "Kishore Kumar, Asha Bhosle - Yeh Raatein Yeh Mausam.mp3",
  "Kishore Kumar - Kiska Rasta Dekhe.mp3",
  "Asha Bhosle, Mohammed Rafi - Abhi Na Jao Chhod Kar.mp3",
  "Hemant Kumar - Hai Apna Dil To Awara.mp3",
  "Kishore Kumar - Ek Ajnabee Haseena Se.mp3",
  "Lata Mangeshkar - Lag Ja Gale Se Phir.mp3",
  "Mukesh, Kanchan - Kya Khoob Lagti Ho.mp3",
  "Hemant Kumar - Jane Woh Kaise Log The (2).mp3",
  "Hemant Kumar - Jane Woh Kaise Log The.mp3",
  "Hemant Kumar - Beqarar Karke Hamen Yun Na Jaiye.mp3",
  "Hemant Kumar - Na Tum Hamen Jano.mp3"
];
